import { AppDatabaseState } from './storageInterface';

export const INITIAL_COMPANY_ID = 'comp-hybrid-001';

export const defaultSeedData: AppDatabaseState = {
  companies: [
    {
      id: INITIAL_COMPANY_ID,
      name: 'Hybrid Civil Engineering & Consultancy',
      slogan: 'Precision Engineering, Structural Integrity & Sustainable Architecture',
      managingDirector: 'Engr. Ashraf',
      managingDirectorQualifications: 'B.Eng, M.Sc.Sc (Structural Engineering), MIEB',
      email: 'info@hybridcivil.com',
      phone: '+880 1712-345678',
      alternativePhone: '+880 1819-876543',
      address: 'Suite 402, Royal Engineering Tower, Green Road, Dhanmondi, Dhaka-1205, Bangladesh',
      logoUrl: '',
      dapRegNo: 'RAJUK/DAP/ENG-2024/098',
      tradeLicense: 'TRAD/DSCC/019284/2023',
      bankDetails: 'Dutch-Bangla Bank Ltd | A/C: 115.120.98451 | Dhanmondi Branch',
      currencySymbol: '৳',
      status: 'active',
      plan: 'Enterprise',
      createdAt: '2025-01-01T08:00:00Z',
      updatedAt: '2026-09-30T08:00:00Z',
    },
    {
      id: 'comp-vertex-002',
      name: 'Vertex Structural Planners & Builders',
      slogan: 'Building Future with Structural Safety',
      managingDirector: 'Engr. K. M. Shamsuddin',
      managingDirectorQualifications: 'B.Sc. Engr (Civil)',
      email: 'contact@vertexplanners.com',
      phone: '+880 1911-223344',
      address: 'House 14, Road 7, Sector 3, Uttara, Dhaka',
      currencySymbol: '৳',
      status: 'active',
      plan: 'Professional',
      createdAt: '2025-06-15T09:00:00Z',
      updatedAt: '2026-09-20T10:00:00Z',
    },
  ],
  clients: [
    {
      id: 'cli-001',
      companyId: INITIAL_COMPANY_ID,
      clientCode: 'HC-CLI-101',
      name: 'Alhajj Mofizur Rahman',
      fatherHusbandName: 'Late Abdul Gafur',
      mobile: '+880 1711-234567',
      alternativeMobile: '+880 1812-345678',
      email: 'mofizur.rahman@example.com',
      address: 'Plot 45, Road 8/A, Dhanmondi R/A, Dhaka-1209',
      nid: '19742698745123654',
      referenceInfo: 'Referred by Engr. Tariq (Architectural Forum)',
      notes: 'VIP Client. High priority for RAJUK Approval drawing and Structural Design.',
      createdAt: '2026-01-10T10:00:00Z',
      updatedAt: '2026-09-25T12:00:00Z',
    },
    {
      id: 'cli-002',
      companyId: INITIAL_COMPANY_ID,
      clientCode: 'HC-CLI-102',
      name: 'Dr. Tariqul Islam',
      fatherHusbandName: 'Prof. Shamsul Huda',
      mobile: '+880 1912-345679',
      alternativeMobile: '+880 1612-998877',
      email: 'dr.tariqul.neuro@gmail.com',
      address: 'Flat 4B, Green Heritage, Panchlaish, Chattogram',
      nid: '19812903847261543',
      referenceInfo: 'Direct office walk-in client',
      notes: 'Planning 6-storey modern residential building with rooftop garden and community hall.',
      createdAt: '2026-02-14T11:30:00Z',
      updatedAt: '2026-09-28T14:20:00Z',
    },
    {
      id: 'cli-003',
      companyId: INITIAL_COMPANY_ID,
      clientCode: 'HC-CLI-103',
      name: 'Engr. Mahbub Alam',
      fatherHusbandName: 'Late Nurul Alam',
      mobile: '+880 1819-765432',
      email: 'mahbub.alam@bengalgroup.com',
      address: 'House 22, Road 5, Block B, Banani, Dhaka',
      nid: '19692847561928374',
      referenceInfo: 'Corporate client (Bengal Real Estate)',
      notes: 'Commercial 8-storey plaza with basement parking.',
      createdAt: '2026-03-01T09:15:00Z',
      updatedAt: '2026-09-29T16:00:00Z',
    },
  ],
  lands: [
    {
      id: 'lnd-001',
      companyId: INITIAL_COMPANY_ID,
      projectId: 'prj-001',
      clientId: 'cli-001',
      landArea: '7.5 Katha',
      decimal: 12.38,
      lengthFeet: 92,
      widthFeet: 55,
      mouza: 'Dhanmondi Mouza',
      khatian: 'BS-4091',
      dagNumber: 'CS-1842 / BS-3940',
      roadWidthFeet: 40,
      frontSetback: '1.50 m (5.0 ft)',
      sideSetback: '1.25 m (4.1 ft)',
      rearSetback: '2.50 m (8.2 ft)',
      landUse: 'Mixed-Use Residential & Commercial',
      location: 'Plot 45, Road 8/A, Dhanmondi R/A, Dhaka',
      googleMapsLink: 'https://maps.google.com/?q=23.7508,90.3739',
      latitude: 23.7508,
      longitude: 90.3739,
      notes: 'Corner plot with dual road frontage (40 ft north, 25 ft east). Clear title deed.',
      createdAt: '2026-01-12T11:00:00Z',
      updatedAt: '2026-01-12T11:00:00Z',
    },
    {
      id: 'lnd-002',
      companyId: INITIAL_COMPANY_ID,
      projectId: 'prj-002',
      clientId: 'cli-002',
      landArea: '5 Katha',
      decimal: 8.25,
      lengthFeet: 75,
      widthFeet: 48,
      mouza: 'Panchlaish',
      khatian: 'RS-1029',
      dagNumber: 'Dag 4492',
      roadWidthFeet: 30,
      frontSetback: '1.50 m',
      sideSetback: '1.00 m',
      rearSetback: '2.00 m',
      landUse: 'Residential',
      location: 'Hill View Road, Panchlaish, Chattogram',
      googleMapsLink: 'https://maps.google.com/?q=22.3683,91.8294',
      latitude: 22.3683,
      longitude: 91.8294,
      notes: 'Moderate slope at rear boundary. Requires soil retaining wall verification.',
      createdAt: '2026-02-16T12:00:00Z',
      updatedAt: '2026-02-16T12:00:00Z',
    },
  ],
  projects: [
    {
      id: 'prj-001',
      companyId: INITIAL_COMPANY_ID,
      projectCode: 'HC-PRJ-2026-01',
      name: 'Al-Haramain Tower',
      clientId: 'cli-001',
      clientName: 'Alhajj Mofizur Rahman',
      projectLocation: 'Road 8/A, Dhanmondi, Dhaka',
      district: 'Dhaka',
      upazila: 'Dhanmondi',
      areaSft: 28500,
      landAreaDecimal: 12.38,
      storeys: 10,
      foundationType: 'Pile Foundation',
      projectType: 'Commercial',
      startDate: '2026-01-15',
      expectedCompletionDate: '2027-06-30',
      currentStage: 'Structure',
      progressPercent: 55,
      status: 'Structure',
      notes: '10-storey commercial building with cast-in-situ bored piles (600mm dia, 65 ft deep).',
      assignedEngineers: {
        managingDirector: 'Engr. Ashraf',
        structuralEngineer: 'Engr. Tanjil Hossain',
        architect: 'Ar. Samira Chowdhury',
        draftEngineer: 'Md. Kamrul Hasan',
        siteEngineer: 'Engr. Rashedul Karim',
      },
      contractAmount: 1850000,
      paidAmount: 1250000,
      dueAmount: 600000,
      createdAt: '2026-01-15T09:00:00Z',
      updatedAt: '2026-09-28T16:00:00Z',
    },
    {
      id: 'prj-002',
      companyId: INITIAL_COMPANY_ID,
      projectCode: 'HC-PRJ-2026-02',
      name: 'Green View Residential Complex',
      clientId: 'cli-002',
      clientName: 'Dr. Tariqul Islam',
      projectLocation: 'Hill View Road, Panchlaish, Chattogram',
      district: 'Chattogram',
      upazila: 'Panchlaish',
      areaSft: 14200,
      landAreaDecimal: 8.25,
      storeys: 6,
      foundationType: 'Combined Footing',
      projectType: 'Residential',
      startDate: '2026-02-20',
      expectedCompletionDate: '2026-12-31',
      currentStage: 'Plaster',
      progressPercent: 78,
      status: 'Plaster',
      notes: '6-Storey residential building. Brickwork complete, plastering and sanitary work in progress.',
      assignedEngineers: {
        managingDirector: 'Engr. Ashraf',
        structuralEngineer: 'Engr. Tanjil Hossain',
        architect: 'Ar. Samira Chowdhury',
        siteEngineer: 'Engr. Rashedul Karim',
      },
      contractAmount: 920000,
      paidAmount: 750000,
      dueAmount: 170000,
      createdAt: '2026-02-20T10:00:00Z',
      updatedAt: '2026-09-29T11:00:00Z',
    },
    {
      id: 'prj-003',
      companyId: INITIAL_COMPANY_ID,
      projectCode: 'HC-PRJ-2026-03',
      name: 'Sunrise Commercial Plaza',
      clientId: 'cli-003',
      clientName: 'Engr. Mahbub Alam',
      projectLocation: 'Subidbazar Main Road, Sylhet',
      district: 'Sylhet',
      upazila: 'Kotwali',
      areaSft: 22000,
      landAreaDecimal: 10.5,
      storeys: 8,
      foundationType: 'Raft Foundation',
      projectType: 'Mixed-Use',
      startDate: '2026-03-10',
      expectedCompletionDate: '2027-04-15',
      currentStage: 'Foundation',
      progressPercent: 32,
      status: 'Foundation',
      notes: 'Raft casting finished last week. Retaining wall and basement column casting underway.',
      assignedEngineers: {
        managingDirector: 'Engr. Ashraf',
        structuralEngineer: 'Engr. Tanjil Hossain',
        siteEngineer: 'Engr. Rashedul Karim',
      },
      contractAmount: 1450000,
      paidAmount: 800000,
      dueAmount: 650000,
      createdAt: '2026-03-10T10:30:00Z',
      updatedAt: '2026-09-27T15:30:00Z',
    },
  ],
  services: [
    {
      id: 'srv-001',
      companyId: INITIAL_COMPANY_ID,
      projectId: 'prj-001',
      clientId: 'cli-001',
      serviceName: 'Structural Design',
      rate: 30,
      quantityScope: '28,500 SFT (10 Storey with Pile cap & shear walls)',
      agreedPrice: 855000,
      discount: 55000,
      finalContractAmount: 800000,
      advance: 300000,
      paid: 600000,
      due: 200000,
      status: 'In Progress',
      notes: 'ETABS 3D dynamic analysis, seismic load according to BNBC 2020.',
      createdAt: '2026-01-16T10:00:00Z',
      updatedAt: '2026-09-20T10:00:00Z',
    },
    {
      id: 'srv-002',
      companyId: INITIAL_COMPANY_ID,
      projectId: 'prj-001',
      clientId: 'cli-001',
      serviceName: 'Architectural Design',
      rate: 22,
      quantityScope: '28,500 SFT Complete Plan, Elevation & Sections',
      agreedPrice: 627000,
      discount: 27000,
      finalContractAmount: 600000,
      advance: 250000,
      paid: 450000,
      due: 150000,
      status: 'Approved',
      notes: 'Full working drawing set delivered and vetted.',
      createdAt: '2026-01-16T10:00:00Z',
      updatedAt: '2026-08-10T10:00:00Z',
    },
    {
      id: 'srv-003',
      companyId: INITIAL_COMPANY_ID,
      projectId: 'prj-001',
      clientId: 'cli-001',
      serviceName: 'Soil Test',
      rate: 15000,
      quantityScope: '3 Boreholes x 65 ft Depth with SPT & Lab Test',
      agreedPrice: 165000,
      discount: 15000,
      finalContractAmount: 150000,
      advance: 100000,
      paid: 150000,
      due: 0,
      status: 'Completed',
      notes: 'Official geotechnical investigation report signed by Engr. Ashraf.',
      createdAt: '2026-01-18T10:00:00Z',
      updatedAt: '2026-02-05T10:00:00Z',
    },
    {
      id: 'srv-004',
      companyId: INITIAL_COMPANY_ID,
      projectId: 'prj-001',
      clientId: 'cli-001',
      serviceName: 'Municipality Approval Drawing',
      rate: 300000,
      quantityScope: 'Full RAJUK Special Project Approval Dossier',
      agreedPrice: 300000,
      discount: 0,
      finalContractAmount: 300000,
      advance: 100000,
      paid: 50000,
      due: 250000,
      status: 'In Progress',
      createdAt: '2026-01-20T10:00:00Z',
      updatedAt: '2026-09-15T10:00:00Z',
    },
  ],
  payments: [
    {
      id: 'pay-001',
      companyId: INITIAL_COMPANY_ID,
      receiptNo: 'HC-RCT-2026-001',
      clientId: 'cli-001',
      clientName: 'Alhajj Mofizur Rahman',
      projectId: 'prj-001',
      projectName: 'Al-Haramain Tower',
      date: '2026-01-18',
      amount: 400000,
      paymentMethod: 'Bank Transfer',
      reference: 'DBBL Trx #98234710',
      receivedBy: 'Engr. Ashraf',
      notes: 'Initial mobilization & design advance',
      createdAt: '2026-01-18T11:00:00Z',
      updatedAt: '2026-01-18T11:00:00Z',
    },
    {
      id: 'pay-002',
      companyId: INITIAL_COMPANY_ID,
      receiptNo: 'HC-RCT-2026-002',
      clientId: 'cli-001',
      clientName: 'Alhajj Mofizur Rahman',
      projectId: 'prj-001',
      projectName: 'Al-Haramain Tower',
      date: '2026-04-10',
      amount: 450000,
      paymentMethod: 'Cheque',
      reference: 'Islami Bank Cheque #492810',
      receivedBy: 'Farhana Haque',
      notes: 'Structural foundation design stage clearance',
      createdAt: '2026-04-10T14:30:00Z',
      updatedAt: '2026-04-10T14:30:00Z',
    },
    {
      id: 'pay-003',
      companyId: INITIAL_COMPANY_ID,
      receiptNo: 'HC-RCT-2026-003',
      clientId: 'cli-001',
      clientName: 'Alhajj Mofizur Rahman',
      projectId: 'prj-001',
      projectName: 'Al-Haramain Tower',
      date: '2026-09-20',
      amount: 400000,
      paymentMethod: 'Bank Transfer',
      reference: 'DBBL Trx #99104812',
      receivedBy: 'Farhana Haque',
      notes: '5th floor structural casting milestone payment',
      createdAt: '2026-09-20T16:00:00Z',
      updatedAt: '2026-09-20T16:00:00Z',
    },
    {
      id: 'pay-004',
      companyId: INITIAL_COMPANY_ID,
      receiptNo: 'HC-RCT-2026-004',
      clientId: 'cli-002',
      clientName: 'Dr. Tariqul Islam',
      projectId: 'prj-002',
      projectName: 'Green View Residential Complex',
      date: '2026-09-28',
      amount: 250000,
      paymentMethod: 'Cheque',
      reference: 'City Bank #819203',
      receivedBy: 'Engr. Ashraf',
      notes: 'Roof casting supervision and completion instalment',
      createdAt: '2026-09-28T12:00:00Z',
      updatedAt: '2026-09-28T12:00:00Z',
    },
  ],
  commitments: [
    {
      id: 'cmt-001',
      companyId: INITIAL_COMPANY_ID,
      clientId: 'cli-001',
      clientName: 'Alhajj Mofizur Rahman',
      projectId: 'prj-001',
      projectName: 'Al-Haramain Tower',
      billAmount: 300000,
      dueAmount: 300000,
      commitmentDate: '2026-10-05',
      description: '7th Floor Slab Casting milestone release',
      status: 'Upcoming',
      notes: 'Client promised to issue cheque upon rebar checking.',
      createdAt: '2026-09-20T10:00:00Z',
      updatedAt: '2026-09-20T10:00:00Z',
    },
    {
      id: 'cmt-002',
      companyId: INITIAL_COMPANY_ID,
      clientId: 'cli-003',
      clientName: 'Engr. Mahbub Alam',
      projectId: 'prj-003',
      projectName: 'Sunrise Commercial Plaza',
      billAmount: 250000,
      dueAmount: 250000,
      commitmentDate: '2026-09-25',
      description: 'Basement Retaining Wall casting instalment',
      status: 'Overdue',
      notes: 'Followed up via phone. Promised to transfer funds by end of week.',
      createdAt: '2026-09-10T12:00:00Z',
      updatedAt: '2026-09-26T09:00:00Z',
    },
    {
      id: 'cmt-003',
      companyId: INITIAL_COMPANY_ID,
      clientId: 'cli-002',
      clientName: 'Dr. Tariqul Islam',
      projectId: 'prj-002',
      projectName: 'Green View Residential Complex',
      billAmount: 170000,
      dueAmount: 170000,
      commitmentDate: '2026-09-30',
      description: 'Plaster stage completion final due',
      status: 'Due Today',
      notes: 'Scheduled for office visit this evening.',
      createdAt: '2026-09-15T15:00:00Z',
      updatedAt: '2026-09-30T08:00:00Z',
    },
  ],
  files: [
    {
      id: 'fil-001',
      companyId: INITIAL_COMPANY_ID,
      fileCode: 'HC-DWG-001',
      projectId: 'prj-001',
      projectName: 'Al-Haramain Tower',
      clientId: 'cli-001',
      clientName: 'Alhajj Mofizur Rahman',
      category: 'Structural',
      fileName: 'Al-Haramain_Pile_Layout_and_Cap_Reinforcement.dwg',
      currentVersion: 'V03',
      status: 'Final',
      versions: [
        {
          versionNumber: 1,
          versionLabel: 'V01 Original',
          uploadDate: '2026-01-25T10:00:00Z',
          uploadedBy: 'Md. Kamrul Hasan (Draft Engineer)',
          fileUrl: '/drawings/prj-001/structural-v01.pdf',
          fileName: 'Al-Haramain_Pile_Layout_V01.dwg',
          fileSize: '4.8 MB',
          description: 'Initial 600mm dia pile layout with 65 ft length based on borehole BH-01.',
          isFinal: false,
        },
        {
          versionNumber: 2,
          versionLabel: 'V02 Correction',
          uploadDate: '2026-02-05T14:30:00Z',
          uploadedBy: 'Engr. Tanjil Hossain (Structural Engineer)',
          fileUrl: '/drawings/prj-001/structural-v02.pdf',
          fileName: 'Al-Haramain_Pile_Layout_V02_Corrected.dwg',
          fileSize: '5.2 MB',
          description: 'Adjusted corner pile spacing to avoid boundary dispute at East corner.',
          correctionNote: 'Client requested 200mm setback clearance at boundary line.',
          isFinal: false,
        },
        {
          versionNumber: 3,
          versionLabel: 'V03 Final',
          uploadDate: '2026-02-15T11:00:00Z',
          uploadedBy: 'Engr. Ashraf (Managing Director)',
          fileUrl: '/drawings/prj-001/structural-v03-final.pdf',
          fileName: 'Al-Haramain_Pile_Layout_V03_Final_Approved.dwg',
          fileSize: '5.4 MB',
          description: 'Final structural working drawing vetted and approved for site execution.',
          correctionNote: 'Incorporated shear link enhancement at column-pile cap interfaces.',
          isFinal: true,
        },
      ],
      createdAt: '2026-01-25T10:00:00Z',
      updatedAt: '2026-02-15T11:00:00Z',
    },
    {
      id: 'fil-002',
      companyId: INITIAL_COMPANY_ID,
      fileCode: 'HC-DWG-002',
      projectId: 'prj-001',
      projectName: 'Al-Haramain Tower',
      clientId: 'cli-001',
      clientName: 'Alhajj Mofizur Rahman',
      category: 'Architectural',
      fileName: 'Al-Haramain_Typical_Floor_Plan_A1.dwg',
      currentVersion: 'V02',
      status: 'Approved',
      versions: [
        {
          versionNumber: 1,
          versionLabel: 'V01 Original',
          uploadDate: '2026-01-20T09:00:00Z',
          uploadedBy: 'Ar. Samira Chowdhury',
          fileUrl: '/drawings/prj-001/arch-v01.pdf',
          fileName: 'Al-Haramain_Typical_Floor_Plan_V01.dwg',
          fileSize: '6.1 MB',
          description: 'Architectural layout with 4 units per floor and 2 elevators.',
          isFinal: false,
        },
        {
          versionNumber: 2,
          versionLabel: 'V02 Correction',
          uploadDate: '2026-02-02T16:00:00Z',
          uploadedBy: 'Ar. Samira Chowdhury',
          fileUrl: '/drawings/prj-001/arch-v02.pdf',
          fileName: 'Al-Haramain_Typical_Floor_Plan_V02.dwg',
          fileSize: '6.3 MB',
          description: 'Modified fire exit staircase width from 1.25m to 1.50m for RAJUK clearance.',
          correctionNote: 'RAJUK Fire Code 2024 compliance revision.',
          isFinal: true,
        },
      ],
      createdAt: '2026-01-20T09:00:00Z',
      updatedAt: '2026-02-02T16:00:00Z',
    },
  ],
  downloads: [
    {
      id: 'dwn-001',
      companyId: INITIAL_COMPANY_ID,
      fileId: 'fil-001',
      fileName: 'Al-Haramain_Pile_Layout_and_Cap_Reinforcement.dwg',
      version: 'V03 Final',
      downloadedBy: 'Engr. Rashedul Karim (Site Engineer)',
      downloadedAt: '2026-02-18T09:45:00Z',
      purpose: 'Field verification and pile boring supervision',
    },
    {
      id: 'dwn-002',
      companyId: INITIAL_COMPANY_ID,
      fileId: 'fil-002',
      fileName: 'Al-Haramain_Typical_Floor_Plan_A1.dwg',
      version: 'V02 Correction',
      downloadedBy: 'M/S Royal Civil Construction',
      downloadedAt: '2026-03-01T14:15:00Z',
      purpose: 'Formwork layout dimension verification',
    },
  ],
  prints: [
    {
      id: 'prt-001',
      companyId: INITIAL_COMPANY_ID,
      fileId: 'fil-001',
      fileName: 'Al-Haramain_Pile_Layout_and_Cap_Reinforcement.dwg',
      version: 'V03 Final',
      printedBy: 'Md. Kamrul Hasan',
      printedAt: '2026-02-16T11:30:00Z',
      printCount: 4,
      notes: 'A1 blueprint prints for Client, Site Office, RAJUK, and Office Archive.',
    },
  ],
  siteVisits: [
    {
      id: 'sv-001',
      companyId: INITIAL_COMPANY_ID,
      projectId: 'prj-001',
      projectName: 'Al-Haramain Tower',
      clientId: 'cli-001',
      clientName: 'Alhajj Mofizur Rahman',
      visitDate: '2026-09-28',
      visitTime: '10:30 AM',
      engineerId: 'emp-004',
      engineerName: 'Engr. Rashedul Karim',
      currentWorkStage: '6th Floor Rebar Binding',
      progressPercent: 55,
      siteCondition: 'Good, dry weather, safety netting installed around perimeter.',
      observation: 'Beam and slab rebars inspected. Clear cover blocks (25mm) placed uniformly.',
      problems: 'Extra top bar curtailment near grid C-3 was short by 150mm.',
      requiredAction: 'Contractor instructed to add 2 Nos 16mm rebar extension with proper lap length before concreting.',
      nextVisitDate: '2026-10-02',
      visitCharge: 5000,
      paid: 5000,
      due: 0,
      photos: [],
      notes: 'Supervision report handed over to client site supervisor.',
      createdAt: '2026-09-28T13:00:00Z',
      updatedAt: '2026-09-28T13:00:00Z',
    },
    {
      id: 'sv-002',
      companyId: INITIAL_COMPANY_ID,
      projectId: 'prj-002',
      projectName: 'Green View Residential Complex',
      clientId: 'cli-002',
      clientName: 'Dr. Tariqul Islam',
      visitDate: '2026-09-30',
      visitTime: '09:00 AM',
      engineerId: 'emp-004',
      engineerName: 'Engr. Rashedul Karim',
      currentWorkStage: 'Plastering & Electrical Conduit Fitting',
      progressPercent: 78,
      siteCondition: 'Clean, curing ponding on 5th floor maintained adequately.',
      observation: 'Plaster mortar ratio 1:4 verified. Surface level and right angle corners checked.',
      problems: 'Minor conduit groove cracking on master bed south wall.',
      requiredAction: 'Apply wire mesh before final plastering coat.',
      nextVisitDate: '2026-10-07',
      visitCharge: 4000,
      paid: 4000,
      due: 0,
      photos: [],
      notes: 'Today morning visit completed.',
      createdAt: '2026-09-30T10:00:00Z',
      updatedAt: '2026-09-30T10:00:00Z',
    },
  ],
  allowances: [
    {
      id: 'alw-001',
      companyId: INITIAL_COMPANY_ID,
      engineerId: 'emp-004',
      engineerName: 'Engr. Rashedul Karim',
      projectId: 'prj-001',
      projectName: 'Al-Haramain Tower',
      visitId: 'sv-001',
      allowanceType: 'Per-visit',
      amount: 1500,
      date: '2026-09-28',
      month: '2026-09',
      status: 'Paid',
      paidDate: '2026-09-28',
      notes: 'Site inspection conveyance & technical allowance',
      createdAt: '2026-09-28T13:30:00Z',
      updatedAt: '2026-09-28T13:30:00Z',
    },
    {
      id: 'alw-002',
      companyId: INITIAL_COMPANY_ID,
      engineerId: 'emp-004',
      engineerName: 'Engr. Rashedul Karim',
      projectId: 'prj-002',
      projectName: 'Green View Residential Complex',
      visitId: 'sv-002',
      allowanceType: 'Per-visit',
      amount: 1500,
      date: '2026-09-30',
      month: '2026-09',
      status: 'Unpaid',
      notes: 'Visit on 30 Sept - pending weekend payroll disbursement',
      createdAt: '2026-09-30T10:30:00Z',
      updatedAt: '2026-09-30T10:30:00Z',
    },
  ],
  employees: [
    {
      id: 'emp-001',
      companyId: INITIAL_COMPANY_ID,
      name: 'Engr. Ashraf',
      position: 'Managing Director & Principal Structural Consultant',
      role: 'Managing Director',
      mobile: '+880 1712-345678',
      email: 'ashraf@hybridcivil.com',
      joiningDate: '2022-01-01',
      salary: 120000,
      status: 'Active',
      assignedProjects: ['prj-001', 'prj-002', 'prj-003'],
      notes: 'B.Eng, M.Sc.Sc (Structural Engineering). Overall engineering approval and leadership.',
      createdAt: '2022-01-01T08:00:00Z',
      updatedAt: '2026-09-01T08:00:00Z',
    },
    {
      id: 'emp-002',
      companyId: INITIAL_COMPANY_ID,
      name: 'Engr. Tanjil Hossain',
      position: 'Senior Structural Engineer',
      role: 'Structural Engineer',
      mobile: '+880 1715-998877',
      email: 'tanjil.structural@hybridcivil.com',
      joiningDate: '2023-03-01',
      salary: 65000,
      status: 'Active',
      assignedProjects: ['prj-001', 'prj-002', 'prj-003'],
      notes: 'Specialist in high-rise concrete structures and BNBC wind/earthquake detailing.',
      createdAt: '2023-03-01T08:00:00Z',
      updatedAt: '2026-09-01T08:00:00Z',
    },
    {
      id: 'emp-003',
      companyId: INITIAL_COMPANY_ID,
      name: 'Ar. Samira Chowdhury',
      position: 'Senior Architect',
      role: 'Architect',
      mobile: '+880 1819-445566',
      email: 'samira.arch@hybridcivil.com',
      joiningDate: '2023-06-15',
      salary: 60000,
      status: 'Active',
      assignedProjects: ['prj-001', 'prj-002'],
      notes: 'B.Arch (BUET). 3D visualization, biophilic design & RAJUK approvals.',
      createdAt: '2023-06-15T08:00:00Z',
      updatedAt: '2026-09-01T08:00:00Z',
    },
    {
      id: 'emp-004',
      companyId: INITIAL_COMPANY_ID,
      name: 'Engr. Rashedul Karim',
      position: 'Senior Site & Quality Engineer',
      role: 'Site Engineer',
      mobile: '+880 1913-778899',
      email: 'rashedul.site@hybridcivil.com',
      joiningDate: '2024-01-10',
      salary: 45000,
      status: 'Active',
      assignedProjects: ['prj-001', 'prj-002', 'prj-003'],
      notes: 'Performs on-site structural inspections, slump tests, and bar bending checking.',
      createdAt: '2024-01-10T08:00:00Z',
      updatedAt: '2026-09-01T08:00:00Z',
    },
    {
      id: 'emp-005',
      companyId: INITIAL_COMPANY_ID,
      name: 'Md. Kamrul Hasan',
      position: 'Chief Draftsman / CAD Engineer',
      role: 'Draft Engineer',
      mobile: '+880 1618-223344',
      email: 'kamrul.cad@hybridcivil.com',
      joiningDate: '2023-01-15',
      salary: 38000,
      status: 'Active',
      assignedProjects: ['prj-001', 'prj-002'],
      notes: 'Master AutoCAD & Revit operator with 8 years detailing experience.',
      createdAt: '2023-01-15T08:00:00Z',
      updatedAt: '2026-09-01T08:00:00Z',
    },
    {
      id: 'emp-006',
      companyId: INITIAL_COMPANY_ID,
      name: 'Farhana Haque',
      position: 'Senior Accountant & Billing Officer',
      role: 'Accountant',
      mobile: '+880 1714-332211',
      email: 'accounts@hybridcivil.com',
      joiningDate: '2023-09-01',
      salary: 40000,
      status: 'Active',
      notes: 'Manages ledger, client billing commitments, payroll, and petty cash vouchers.',
      createdAt: '2023-09-01T08:00:00Z',
      updatedAt: '2026-09-01T08:00:00Z',
    },
  ],
  contractors: [
    {
      id: 'cnt-001',
      companyId: INITIAL_COMPANY_ID,
      name: 'Engr. Nurul Islam',
      companyName: 'M/S Royal Civil Construction',
      mobile: '+880 1711-889900',
      trade: 'Civil',
      projectId: 'prj-001',
      projectName: 'Al-Haramain Tower',
      workScope: 'Complete RCC structural frame, casting, curing, and brickwork up to 10th floor',
      contractAmount: 8500000,
      paid: 5200000,
      due: 3300000,
      startDate: '2026-02-01',
      expectedCompletion: '2027-02-28',
      status: 'Active',
      notes: 'Good execution track record. Modern shuttering equipment deployed.',
      createdAt: '2026-02-01T09:00:00Z',
      updatedAt: '2026-09-20T10:00:00Z',
    },
    {
      id: 'cnt-002',
      companyId: INITIAL_COMPANY_ID,
      name: 'Haji Shamsuddin',
      companyName: 'Metro Sanitary & Plumbing Works',
      mobile: '+880 1817-665544',
      trade: 'Plumbing',
      projectId: 'prj-002',
      projectName: 'Green View Residential Complex',
      workScope: 'Concealed CPVC/PPR pipeline, water supply lines, septic tank, and drainage conduits',
      contractAmount: 480000,
      paid: 320000,
      due: 160000,
      startDate: '2026-04-15',
      expectedCompletion: '2026-11-30',
      status: 'Active',
      notes: 'Work progressing satisfactorily.',
      createdAt: '2026-04-15T09:00:00Z',
      updatedAt: '2026-09-25T11:00:00Z',
    },
  ],
  middlemen: [
    {
      id: 'mid-001',
      companyId: INITIAL_COMPANY_ID,
      name: 'Advocate Shafiul Alam',
      mobile: '+880 1718-223344',
      clientId: 'cli-001',
      clientName: 'Alhajj Mofizur Rahman',
      projectId: 'prj-001',
      projectName: 'Al-Haramain Tower',
      commission: 50000,
      commissionType: 'Fixed',
      paid: 30000,
      due: 20000,
      date: '2026-01-20',
      notes: 'Introduced client for design and consultancy contract.',
      createdAt: '2026-01-20T10:00:00Z',
      updatedAt: '2026-09-10T10:00:00Z',
    },
  ],
  soilTests: [
    {
      id: 'st-001',
      companyId: INITIAL_COMPANY_ID,
      testCode: 'HC-ST-2026-01',
      clientId: 'cli-001',
      clientName: 'Alhajj Mofizur Rahman',
      projectId: 'prj-001',
      projectName: 'Al-Haramain Tower',
      location: 'Plot 45, Road 8/A, Dhanmondi R/A, Dhaka',
      boreholeId: 'BH-01',
      groundLevelFeet: 0.0,
      groundwaterLevelFeet: 8.5,
      totalDepthFeet: 50,
      testDate: '2026-01-18',
      laboratory: 'Hybrid Civil Geotechnical Testing Laboratory',
      engineerName: 'Engr. Ashraf B.Eng, M.Sc.Sc (Structural Engineering)',
      notes: 'Wash boring method carried out using split-spoon sampler (1.5" ID, 2" OD) with 63.5 kg hammer falling free from 760mm height (ASTM D1586).',
      sptTable: [
        {
          depthFeet: 5,
          sampleNumber: 'SS-01',
          blows: '2-3-3',
          nValue: 6,
          soilDescription: 'Dark grey soft clayey silt with organic traces',
          sampleType: 'Split Spoon',
          remarks: 'High compressibility',
        },
        {
          depthFeet: 10,
          sampleNumber: 'SS-02',
          blows: '3-4-5',
          nValue: 9,
          soilDescription: 'Grey medium stiff silty clay',
          sampleType: 'Split Spoon',
          remarks: 'Groundwater struck at 8.5 ft',
        },
        {
          depthFeet: 15,
          sampleNumber: 'SS-03',
          blows: '4-6-7',
          nValue: 13,
          soilDescription: 'Light brown medium stiff clayey silt',
          sampleType: 'Split Spoon',
          remarks: 'Low plasticity',
        },
        {
          depthFeet: 20,
          sampleNumber: 'SS-04',
          blows: '5-8-10',
          nValue: 18,
          soilDescription: 'Brownish medium dense fine sand with silt',
          sampleType: 'Split Spoon',
          remarks: 'Transition strata',
        },
        {
          depthFeet: 25,
          sampleNumber: 'SS-05',
          blows: '7-11-13',
          nValue: 24,
          soilDescription: 'Light yellowish brown dense fine to medium sand',
          sampleType: 'Split Spoon',
          remarks: 'Submerged condition',
        },
        {
          depthFeet: 30,
          sampleNumber: 'SS-06',
          blows: '9-14-15',
          nValue: 29,
          soilDescription: 'Dense silty fine sand with mica flakes',
          sampleType: 'Split Spoon',
          remarks: 'Good bearing capability',
        },
        {
          depthFeet: 35,
          sampleNumber: 'SS-07',
          blows: '11-16-18',
          nValue: 34,
          soilDescription: 'Very dense yellowish grey fine to medium sand',
          sampleType: 'Split Spoon',
          remarks: 'Hard strata',
        },
        {
          depthFeet: 40,
          sampleNumber: 'SS-08',
          blows: '14-19-21',
          nValue: 40,
          soilDescription: 'Very dense compact sand with gravel traces',
          sampleType: 'Split Spoon',
          remarks: 'Ideal pile founding layer',
        },
        {
          depthFeet: 45,
          sampleNumber: 'SS-09',
          blows: '16-22-24',
          nValue: 46,
          soilDescription: 'Extremely dense coarse to medium sand layer',
          sampleType: 'Split Spoon',
          remarks: 'Refusal condition approaches',
        },
        {
          depthFeet: 50,
          sampleNumber: 'SS-10',
          blows: '18-25-27',
          nValue: 52,
          soilDescription: 'Extremely dense compact sand and hard clay matrix',
          sampleType: 'Split Spoon',
          remarks: 'Borehole terminated at 50 ft',
        },
      ],
      recommendation: {
        recommendedFoundation: 'Cast-in-situ RCC Bored Pile Foundation',
        recommendedFoundingDepthFeet: 45,
        allowableBearingCapacityKsf: 4.8,
        groundwaterConsideration: 'Permanent groundwater table located at 8.5 ft below existing GL. Bentonite slurry drilling required for pile boring.',
        settlementConsideration: 'Calculated immediate elastic settlement < 12mm; consolidated differential settlement within BNBC tolerance limits.',
        soilImprovement: 'No chemical grouting needed if pile tips rest solidly in the very dense sand layer below 40 ft.',
        specialNotes: 'For a 10-storey building with heavy column axial reactions (up to 450 metric tons), shallow foundations are strictly inadvisable due to soft top strata (N=6 to 9 in top 10 ft). Pile capacity: 600mm dia pile estimated safe working capacity = 110 MT.',
        approvedByEngineer: 'Engr. Ashraf B.Eng, M.Sc.Sc (Structural Engineering)',
        approvalDate: '2026-01-22',
      },
      createdAt: '2026-01-18T16:00:00Z',
      updatedAt: '2026-01-22T12:00:00Z',
    },
  ],
  salaries: [
    {
      id: 'sal-001',
      companyId: INITIAL_COMPANY_ID,
      employeeId: 'emp-002',
      employeeName: 'Engr. Tanjil Hossain',
      month: '2026-08',
      basicSalary: 65000,
      advance: 5000,
      deduction: 0,
      bonus: 5000,
      paid: 65000,
      due: 0,
      paymentDate: '2026-09-05',
      notes: 'August 2026 salary disbursed via bank transfer',
      createdAt: '2026-09-01T10:00:00Z',
      updatedAt: '2026-09-05T10:00:00Z',
    },
    {
      id: 'sal-002',
      companyId: INITIAL_COMPANY_ID,
      employeeId: 'emp-004',
      employeeName: 'Engr. Rashedul Karim',
      month: '2026-09',
      basicSalary: 45000,
      advance: 10000,
      deduction: 0,
      bonus: 0,
      paid: 20000,
      due: 15000,
      notes: 'Partial advance disbursed on 15 Sept; balance due on 1st October',
      createdAt: '2026-09-25T10:00:00Z',
      updatedAt: '2026-09-25T10:00:00Z',
    },
  ],
  expenses: [
    {
      id: 'exp-001',
      companyId: INITIAL_COMPANY_ID,
      expenseCode: 'HC-EXP-001',
      date: '2026-09-02',
      category: 'Office Rent',
      amount: 45000,
      paidBy: 'Engr. Ashraf',
      description: 'Dhanmondi office floor monthly rent payment for September 2026',
      notes: 'Paid via cheque to building landlord',
      createdAt: '2026-09-02T10:00:00Z',
      updatedAt: '2026-09-02T10:00:00Z',
    },
    {
      id: 'exp-002',
      companyId: INITIAL_COMPANY_ID,
      expenseCode: 'HC-EXP-002',
      date: '2026-09-12',
      category: 'Printing',
      amount: 14500,
      projectId: 'prj-001',
      projectName: 'Al-Haramain Tower',
      paidBy: 'Farhana Haque',
      description: 'A1 blueprint plots, structural sets binding and RAJUK drawing submissions',
      notes: 'Al-Madina Digital Plotters invoice #892',
      createdAt: '2026-09-12T14:00:00Z',
      updatedAt: '2026-09-12T14:00:00Z',
    },
    {
      id: 'exp-003',
      companyId: INITIAL_COMPANY_ID,
      expenseCode: 'HC-EXP-003',
      date: '2026-09-18',
      category: 'Electricity',
      amount: 8750,
      paidBy: 'Farhana Haque',
      description: 'DPDC office electricity bill payment',
      createdAt: '2026-09-18T11:00:00Z',
      updatedAt: '2026-09-18T11:00:00Z',
    },
    {
      id: 'exp-004',
      companyId: INITIAL_COMPANY_ID,
      expenseCode: 'HC-EXP-004',
      date: '2026-09-22',
      category: 'Tea/Food',
      amount: 4200,
      paidBy: 'Farhana Haque',
      description: 'Office snacks, tea, guest hospitality & monthly pantry groceries',
      createdAt: '2026-09-22T16:00:00Z',
      updatedAt: '2026-09-22T16:00:00Z',
    },
  ],
  advertisements: [
    {
      id: 'adv-001',
      companyId: INITIAL_COMPANY_ID,
      date: '2026-09-05',
      platform: 'Facebook',
      campaign: 'Dhanmondi & Gulshan Landowners Modern Building Design Campaign',
      amount: 12500,
      paidBy: 'Engr. Ashraf',
      notes: 'Targeted high-net-worth property owners; generated 18 qualified inquiries',
      createdAt: '2026-09-05T12:00:00Z',
      updatedAt: '2026-09-05T12:00:00Z',
    },
    {
      id: 'adv-002',
      companyId: INITIAL_COMPANY_ID,
      date: '2026-09-15',
      platform: 'Google',
      campaign: 'Google Search Ads: Civil Engineering & Soil Testing Dhaka',
      amount: 8500,
      paidBy: 'Engr. Ashraf',
      notes: 'High conversion keywords: BNBC 2020 Structural Design, Soil test cost Dhaka',
      createdAt: '2026-09-15T10:00:00Z',
      updatedAt: '2026-09-15T10:00:00Z',
    },
  ],
  boksis: [
    {
      id: 'bok-001',
      companyId: INITIAL_COMPANY_ID,
      date: '2026-09-14',
      projectId: 'prj-001',
      projectName: 'Al-Haramain Tower',
      clientId: 'cli-001',
      clientName: 'Alhajj Mofizur Rahman',
      recipient: 'Municipality / RAJUK Desk Peon',
      purpose: 'Expediting file dispatch and docketing',
      amount: 1500,
      paidBy: 'Md. Kamrul Hasan',
      notes: 'Field documentation dispatch',
      createdAt: '2026-09-14T15:00:00Z',
      updatedAt: '2026-09-14T15:00:00Z',
    },
    {
      id: 'bok-002',
      companyId: INITIAL_COMPANY_ID,
      date: '2026-09-28',
      projectId: 'prj-001',
      projectName: 'Al-Haramain Tower',
      clientId: 'cli-001',
      clientName: 'Alhajj Mofizur Rahman',
      recipient: 'Site Gate Guard & Labor Foreman',
      purpose: 'Night slab casting supervision hospitality boksis',
      amount: 1000,
      paidBy: 'Engr. Rashedul Karim',
      notes: 'During 6th floor night concreting check',
      createdAt: '2026-09-28T22:00:00Z',
      updatedAt: '2026-09-28T22:00:00Z',
    },
  ],
  transactions: [
    {
      id: 'trx-001',
      companyId: INITIAL_COMPANY_ID,
      date: '2026-09-20',
      type: 'Income',
      amount: 400000,
      category: 'Client Milestone Collection',
      clientId: 'cli-001',
      projectId: 'prj-001',
      person: 'Alhajj Mofizur Rahman',
      description: '5th floor structural casting milestone payment received',
      reference: 'DBBL Trx #99104812',
      createdBy: 'Farhana Haque',
      createdAt: '2026-09-20T16:00:00Z',
      updatedAt: '2026-09-20T16:00:00Z',
    },
    {
      id: 'trx-002',
      companyId: INITIAL_COMPANY_ID,
      date: '2026-09-28',
      type: 'Income',
      amount: 250000,
      category: 'Client Milestone Collection',
      clientId: 'cli-002',
      projectId: 'prj-002',
      person: 'Dr. Tariqul Islam',
      description: 'Roof casting supervision instalment',
      reference: 'City Bank #819203',
      createdBy: 'Farhana Haque',
      createdAt: '2026-09-28T12:00:00Z',
      updatedAt: '2026-09-28T12:00:00Z',
    },
    {
      id: 'trx-003',
      companyId: INITIAL_COMPANY_ID,
      date: '2026-09-02',
      type: 'Expense',
      amount: 45000,
      category: 'Office Rent',
      person: 'Building Landlord',
      description: 'Office rent September 2026',
      reference: 'CHQ-89012',
      createdBy: 'Farhana Haque',
      createdAt: '2026-09-02T10:00:00Z',
      updatedAt: '2026-09-02T10:00:00Z',
    },
  ],
  auditLogs: [
    {
      id: 'aud-001',
      companyId: INITIAL_COMPANY_ID,
      user: 'Engr. Ashraf',
      action: 'LOGIN',
      module: 'Auth',
      recordId: 'emp-001',
      details: 'Principal Consultant Engr. Ashraf authenticated into management console.',
      timestamp: '2026-09-30T07:30:00Z',
    },
    {
      id: 'aud-002',
      companyId: INITIAL_COMPANY_ID,
      user: 'Farhana Haque',
      action: 'PAYMENT',
      module: 'Payments',
      recordId: 'pay-004',
      details: 'Recorded payment of ৳250,000 from Dr. Tariqul Islam for Green View Residential Complex.',
      timestamp: '2026-09-28T12:05:00Z',
    },
    {
      id: 'aud-003',
      companyId: INITIAL_COMPANY_ID,
      user: 'Engr. Ashraf',
      action: 'CORRECTION',
      module: 'Files',
      recordId: 'fil-001',
      details: 'Approved V03 Final version for Al-Haramain Pile Layout drawing.',
      timestamp: '2026-02-15T11:05:00Z',
    },
  ],
  notifications: [
    {
      id: 'notif-001',
      companyId: INITIAL_COMPANY_ID,
      type: 'payment_due',
      title: 'Payment Due Today: Dr. Tariqul Islam',
      message: 'Bill commitment of ৳170,000 for Green View Residential is scheduled for clearance today.',
      date: '2026-09-30',
      read: false,
      linkTab: 'commitments',
      createdAt: '2026-09-30T06:00:00Z',
    },
    {
      id: 'notif-002',
      companyId: INITIAL_COMPANY_ID,
      type: 'payment_overdue',
      title: 'Overdue Commitment: Engr. Mahbub Alam',
      message: 'Basement retaining wall instalment of ৳250,000 was due on 25-09-2026 (5 days overdue).',
      date: '2026-09-25',
      read: false,
      linkTab: 'commitments',
      createdAt: '2026-09-26T08:00:00Z',
    },
    {
      id: 'notif-003',
      companyId: INITIAL_COMPANY_ID,
      type: 'visit_due',
      title: 'Upcoming Site Visit: Al-Haramain Tower',
      message: 'Site inspection scheduled on 02-10-2026 by Engr. Rashedul Karim for 6th floor casting.',
      date: '2026-10-02',
      read: false,
      linkTab: 'siteVisits',
      createdAt: '2026-09-28T13:00:00Z',
    },
    {
      id: 'notif-004',
      companyId: INITIAL_COMPANY_ID,
      type: 'salary_due',
      title: 'Salary Due Notice: Engr. Rashedul Karim',
      message: 'Balance salary due of ৳15,000 for September 2026 pending disbursement.',
      date: '2026-09-30',
      read: true,
      linkTab: 'team',
      createdAt: '2026-09-25T10:00:00Z',
    },
  ],
};
